### ISSUE TITLE
validation of nested elements does not work

### ISSUE THREAD

**Issue by fsimmend** [klum-dsl/klum-ast#25]
it seems as if the validate annotation is only working in the most toplevel dsl class

**Comment by pauxus** [comment]
Can you describe your test case?

Given this setup:

``` groovy
            @DSL
            class Foo {
                @Validate
                String validated

                @Validate
                Inner inner
            }

            @DSL
            class Inner {
                @Validate
                String value
            }
```
- If an instance of foo is created, validation fails, because `inner` is null
- if an instance of foo is created with an instance of inner with a missing `value` it fails
- If the @Validate annotation is removed from inner, it works either if no inner instance is created or if that instance is correctly validated

This seems to work as designed. However it might be possible to adjust the behaviour, if a different on makes more sense

**Comment by pauxus** [comment]
Ok, seems I was to quick, the added test fails, so I can reproduce the issue.
